### ISSUE TITLE
Turkish GDPR link

### ISSUE THREAD

**Issue by esinozturk** [con/open-brain-consent#94]
Hi,
I would like to ask if you could add a link to Turkish GDPR in the content table? Thanks,
Esin

**Comment by yarikoptic** [comment]
what do you mean exactly? I see Turkish listed within https://open-brain-consent.readthedocs.io/en/stable/gdpr/data_user_agreement.html#translations

**Comment by esinozturk** [comment]
Hi, 

A link is missing at: 

https://open-brain-consent.readthedocs.io/en/stable/index.html 

Thank you, sincerely, 

Esin 

On 2020-09-08 15:35, Yaroslav Halchenko wrote:

> what do you mean exactly? I see Turkish listed within https://open-brain-consent.readthedocs.io/en/stable/gdpr/data_user_agreement.html#translations 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

-- 
Assoc. Prof. Esin Öztürk Işık
Boğaziçi University
Institute of Biomedical Engineering
Kandilli Campus
Kandilli Mah Rasathane Cad
34684 Çengelköy, Istanbul, TURKEY
Phone: +90(216)516-3463
Website: https://cil.boun.edu.tr, http://www.esinozturkisik.com 

Links:
------
[1]
https://github.com/con/open-brain-consent/issues/94#issuecomment-688836799
[2]

**Comment by yarikoptic** [comment]
That page doesn't list individual translations for GDPR version (only for the original ultimate)  - you need to click on "Translations". I guess we should look into unifying it but IIRC I found not quick/easy way when I did that.  I will close this one (since there is no missing link to Turkish translation as opposed to the other translations), but feel free to reopen
